[tool.poetry]
name = "turing_data_transformation_library"
version = "0.1.2"
description = ""
authors = ["Vytautas Pliadis <vytautas.pliadis@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11.0"
pytest = "^7.4.3"
numpy = "^1.26.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"