[tool.poetry]
name = "prot2d"
version = "0.1.12"
description = "Package for creating simplified 2D visualisation for input protein. Specialised on showing differences and similaritys between proteins from the same proteinfamily."
authors = ["constantincarl <ge37goy@mytum.de>"]
readme = "README.md"

include = ["PROT2D/SF_database/*"]


[tool.poetry.dependencies]
python = ">=3.10,<3.13"
biopython = "^1.81"
networkx = "^3.2"
svgwrite = "^1.4.3"
shapely = "^2.0.2"
tqdm = "^4.66.1"
vtk = "^9.2.6"
colour = "^0.1.5"
scipy = "^1.11.3"
pandas = "^2.1.3"
anytree = "^2.12.1"
wget = "^3.2"
seaborn = "^0.13.0"
h5py = "^3.10.0"
alphashape = "^1.3.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.27.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
