[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "coopertunes"
version = "0.2.0"
authors = [
  { name="Åukasz Bondaruk", email="lukas.bond07@gmail.com" },
  { name="Oskar Bartosz", email="oskbsz@gmail.com" },
  { name="Andrzej Kusiak", email="andrzej.kusiak00@gmail.com" }]
description = "Hub for music machine learning  generating audio"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "coloredlogs>=15.0.1",
  "deepspeed==0.12.5",
  "einops==0.7.0",
  "pycodestyle==2.10.0",
  "pylint==2.16.2",
  "tensorboard==2.15.1",
  "mypy==1.5.0",
  "matplotlib==3.8.2",
  "numpy==1.23.5",
  "librosa==0.9.1",
  "scipy==1.11.4",
  "argparse==1.4.0",
  "torch-summary==1.4.5",
  "pretty_midi==0.2.10",
  "progress==1.6",
  "black==23.12.1",
  "torch==2.0.1",
  "torchaudio==2.0.2",
  "requests==2.31.0",
  "types-requests==2.31.0.20240106",
  "beautifulsoup4==4.12.2"]

[project.urls]
"Homepage" = "https://github.com/Szakulli07/coopertunes"

[tool.setuptools.package-dir]
coopertunes = "coopertunes"

[pycodestyle]
max-line-length = 100

[tool.pylint.MAIN]
fail-under = 10

[tool.pylint.DESIGN]
max-args = 12

[tool.pylint.'MESSAGES CONTROL']
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "duplicate-code",
  "too-many-locals",
  "too-many-branches",
  "too-many-instance-attributes",
  "too-many-statements",
  "too-few-public-methods",
  "consider-using-from-import",
  "invalid-name"]

[tool.pylint.TYPECHECK]
generated-members = "torch.*"
