[tool.poetry]
name = "ifn"
version = "0.0.1"
description = ""
authors = ["baa <baagod@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
