[tool.poetry]
name = "lara-cli"
version = "0.2.0"
description = ""
authors = ["Lara Health Engineering <engineering@lara.health>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.1.7"
requests = "^2.31.0"
rich = "^13.7.0"
sentry-sdk = "^1.39.2"
pick = "^2.2.0"
arrow = "^1.3.0"


[[tool.poetry.source]]
name = "lara"
url = "https://pypi.org/"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
lara = "lara_cli.cli:cli"
