[build-system]
requires = ["flit_core>=3.9"]
build-backend = "flit_core.buildapi"

[project.scripts]
junocli = "junoplatform.tools.cmd:main"

[project]
name = "junoplatform"
version = "1.4.5"
authors = [{ name = "Bruce.Lu", email = "lzbgt@icloud.com" }]
description = "juno AI platform lib"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = [
  "flit_core >=3.9.0",
  "requests",
  "pulsar-client",
  "numpy",
  "python-decouple",
  "pyyaml",
  "clickhouse-connect",
  "pymongo",
  "questdb",
  "postgres",
  "cryptography",
  "bcrypt",
  "redis",
  "pylint",
  "elasticsearch",
  "dateparser",
  "pydantic>=1.10.12",
  "oss2",
  "click",
  "findimports",
  "pyzmq",
  "pycryptodome",
]

[project.urls]
"Homepage" = "https://github.com/lzbgt/sampleproject"
"Bug Tracker" = "https://github.com/lzbgt/sampleproject/issues"
