[build-system]
requires = ['setuptools==68.0.0']
build-backend = 'setuptools.build_meta'

[project]
name = 'searchpi'
version = '0.0.1'
authors = [
  { name='Evgeniy Blinov', email='zheni-b@yandex.ru' },
]
description = 'A command-line tool for searching your Raspberry Pi in a local network'
readme = 'README.md'
requires-python = '>=3.9'
dependencies = [
    'paramiko==3.4.0',
    'typer==0.9.0',
]
classifiers = [
  'Operating System :: MacOS :: MacOS X',
  'Operating System :: POSIX',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'License :: OSI Approved :: MIT License',
  'Topic :: Software Development :: Libraries',
  'Topic :: Utilities',
  'Intended Audience :: System Administrators',
]

[project.scripts]
searchpi = 'searchpi.main:main'

[project.urls]
'Source' = 'https://github.com/pomponchik/searchpi'
'Tracker' = 'https://github.com/pomponchik/searchpi/issues'
