[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "inter-jamisson"
dynamic = ["version"]
description = ''
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "jjader", email = "jamisson.junior@a3data.com.br" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["pandas==2.0.3","click", "scikit-learn==1.3.2", "cookiecutter==2.2.3"]

[project.urls]
Documentation = "https://github.com/unknown/inter-jamisson#readme"
Issues = "https://github.com/unknown/inter-jamisson/issues"
Source = "https://github.com/unknown/inter-jamisson"

[project.scripts]
inter = "inter_jamisson.cli:inter"

[tool.hatch.version]
path = "src/inter_jamisson/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
[tool.hatch.envs.default.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]

[tool.hatch.envs.lint]
skip-install = true
dependencies = [
  "flake8==6.0.0","black==23.3.0","isort==5.12.0"
]

[tool.hatch.envs.lint.scripts]
run = [
    "isort src/ tests/",
    "black src/ tests/",
    "flake8 src/ tests/"
]
check = [
  "flake8 .",
  "black --check --diff .",
  "isort --check-only --diff .",
]

[[tool.hatch.envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[tool.hatch.envs.types]
dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/inter_jamisson tests}"

[tool.coverage.run]
source_pkgs = ["inter_jamisson", "tests"]
branch = true
parallel = true
omit = [
  "src/inter_jamisson/__about__.py",
]

[tool.coverage.paths]
inter_jamisson = ["src/inter_jamisson", "*/inter-jamisson/src/inter_jamisson"]
tests = ["tests", "*/inter-jamisson/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"

# [project]
# name = "inter"
# dynamic = ["version"]
# description = ''
# readme = "README.md"
# requires-python = ">=3.8"
# license = "MIT"
# keywords = []
# authors = [
#   { name = "jjader", email = "jamisson.junior@a3data.com.br" },
# ]
# classifiers = [
#   "Development Status :: 4 - Beta",
#   "Programming Language :: Python",
#   "Programming Language :: Python :: 3.8",
#   "Programming Language :: Python :: 3.9",
#   "Programming Language :: Python :: 3.10",
#   "Programming Language :: Python :: 3.11",
#   "Programming Language :: Python :: 3.12",
#   "Programming Language :: Python :: Implementation :: CPython",
#   "Programming Language :: Python :: Implementation :: PyPy",
# ]
# dependencies = ["pandas==2.0.3","click", "scikit-learn==1.3.2", "cookiecutter==2.2.3"]

# [project.urls]
# Documentation = "https://github.com/unknown/inter#readme"
# Issues = "https://github.com/unknown/inter/issues"
# Source = "https://github.com/unknown/inter"

# [project.scripts]
# inter = "inter.cli:inter"

# [tool.hatch.version]
# path = "src/inter/__about__.py"

# [tool.hatch.envs.default]
# dependencies = [
#   "coverage[toml]>=6.5",
#   "pytest"
# ]
# [tool.hatch.envs.default.scripts]
# test = "pytest {args:tests}"
# test-cov = "coverage run -m pytest {args:tests}"
# cov-report = [
#   "- coverage combine",
#   "coverage report",
# ]
# cov = [
#   "test-cov",
#   "cov-report",
# ]

# [[tool.hatch.envs.all.matrix]]
# python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

# [tool.hatch.envs.types]
# dependencies = [
#   "mypy>=1.0.0",
# ]
# [tool.hatch.envs.types.scripts]
# check = "mypy --install-types --non-interactive {args:src/inter tests}"


# [tool.hatch.envs.lint]
# detached = true

# [tool.hatch.envs.docs]
# dependencies = [
#   "mkdocs"
# ]
# [tool.hatch.envs.docs.scripts]
# build = "mkdocs build --clean --strict"
# serve = "mkdocs serve --dev-addr localhost:8000"

# [tool.coverage.run]
# source_pkgs = ["inter", "tests"]
# branch = true
# parallel = true
# omit = [
#   "src/inter/__about__.py",
# ]

# [tool.coverage.paths]
# inter = ["src/inter", "*/inter/src/inter"]
# tests = ["tests", "*/inter/tests"]

# [tool.coverage.report]
# exclude_lines = [
#   "no cov",
#   "if __name__ == .__main__.:",
#   "if TYPE_CHECKING:",
# ]
