[tool.poetry]
name = "ttnet"
version = "0.1.6"
description = ""
license = "MIT"
authors = ["Davide Vega D'Aurelio <dvladek@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
result = "^0.14.0"
pandas = "^2.1.3"
uunet = "2.1"
networkx = "^3.2.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
