[project]
name = "shieldcloudapi"
version = "0.2.14"
authors = [
  { name="John Edwards", email="john.edwards@intrusion.com" },
]
description = "Intrusion Inc Shield Cloud API package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://developer.intrusion.com"
"Bug Tracker" = "https://github.com/Jarvis-Int-Inc/shieldpython/issues"

[build-system]
requires = ["setuptools>=57"]
build-backend = "setuptools.build_meta"

