[tool.poetry]
name = "nagra_network_paloalto_utils"
version = "0.1.14"
description = ""
authors = ["David Gallay <david.gallay@nagra.com>"]
readme = "README.md"
packages = [{include = "nagra_network_paloalto_utils", from="."}]

[tool.poetry.scripts]
paloalto_utils = "nagra_network_paloalto_utils.__main__:main"
pautils = "nagra_network_paloalto_utils.__main__:main"

[tool.poetry.dependencies]
python = "^3.9"
pyyaml = ">=0.2.5"
gitpython = ">=0.3.6"
colorama = ">=0.4.4"
urllib3 = ">=1.26.4"
ruamel-yaml = ">=0.17.21"
xmltodict = ">=0.13.0"
click = "^8.1.7"
nagra-panorama-api = "^0.1.12"
requests = "^2.31.0"
glom = "^23.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
